//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FiveP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin_Notification
    {
        public int admin_notification_id { get; set; }
        public string admin_notification_content { get; set; }
        public Nullable<System.DateTime> admin_notification_datecreate { get; set; }
        public Nullable<bool> admin_notification_status { get; set; }
    }
}
