//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FiveP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Like_Reply_Post
    {
        public int like_reply_post_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<bool> like_reply_post_likeORdis { get; set; }
        public Nullable<System.DateTime> like_reply_post_datecreated { get; set; }
        public Nullable<System.DateTime> like_reply_post_dateedit { get; set; }
    
        public virtual User User { get; set; }
    }
}
