//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FiveP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessageBosFiveP
    {
        public int bossfivep_id { get; set; }
        public string quesstion { get; set; }
        public string reply { get; set; }
        public Nullable<System.DateTime> datetime { get; set; }
    }
}
