//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FiveP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tag
    {
        public int tags_id { get; set; }
        public Nullable<int> post_id { get; set; }
        public Nullable<System.DateTime> tags_datetime { get; set; }
        public string tags_name { get; set; }
    
        public virtual Post Post { get; set; }
    }
}
